universe = vanilla 
Executable = exe_NONE_ST_tW-channel_antitop_MC_2017.sh 
Arguments = $(Process) 
Should_Transfer_Files = YES 
WhenToTransferOutput = ON_EXIT 
Transfer_Input_Files = input.tar 
Output = ctagana_$(Cluster)_$(Process).stdout 
Error = ctagana_$(Cluster)_$(Process).stderr 
Log = ctagana_$(Cluster)_$(Process).log 
notify_user = ${LOGNAME}@FNAL.GOV 
+LENGTH="SHORT" 
x509userproxy = $ENV(X509_USER_PROXY) 
Queue 24
